import type { FacilityId, GameState, ResourceDefinition, ResourceId, StoragePoolId } from "./types";

type ResourceRates = Partial<Record<ResourceId, number>>;
type UpgradeMaterials = Partial<Record<ResourceId, number>>;

const resource = (
  name: string,
  unit: string,
  baseValue: number,
  category: ResourceDefinition["category"],
  poolId?: StoragePoolId,
): ResourceDefinition => ({
  name,
  unit,
  baseValue,
  category,
  ...(poolId ? { poolId } : {}),
});

const req = (level: number, ...facilityIds: FacilityId[]) => facilityIds.map((facilityId) => ({ facilityId, level }));

const fac = (
  id: FacilityId,
  name: string,
  inputRate: ResourceRates,
  outputRate: ResourceRates,
  powerConsumption: number,
  cash: number,
  materials: UpgradeMaterials = {},
  unlockRequirements: Array<{ facilityId: FacilityId; level: number }> = [],
  unlocked = true,
  baseUpkeep = 0,
  workersNeeded = 0,
  tier = 1,
) => ({
  id,
  name,
  level: 0,
  enabled: false,
  active: false,
  status: "online" as const,
  inputRate,
  outputRate,
  powerConsumption,
  baseUpkeep,
  workersNeeded,
  tier,
  unlocked,
  unlockRequirements,
  upgrade: { base: { cash, materials }, growth: 1.75 },
});

<<<<<<< HEAD
export const RESOURCE_DEFINITIONS: Record<ResourceId, ResourceDefinition> = {
  power: resource("Power", "MW", 4, "energy"),
  coal: resource("Coal", "t", 12, "raw", "ore"),
  ironOre: resource("Iron Ore", "t", 18, "raw", "ore"),
  copperOre: resource("Copper Ore", "t", 28, "raw", "ore"),
  bauxite: resource("Bauxite", "t", 14, "raw", "ore"),
  silica: resource("Silica", "t", 16, "raw", "ore"),
  crudeOil: resource("Crude Oil", "bbl", 22, "raw", "liquid"),
  water: resource("Water", "kL", 2, "construction", "liquid"),
  limestone: resource("Limestone", "t", 10, "raw", "ore"),
  titaniumOre: resource("Titanium Ore", "t", 24, "raw", "ore"),
  uraniumOre: resource("Uranium Ore", "t", 25, "raw", "radioactive"),
  naturalGas: resource("Natural Gas", "kNm³", 20, "raw", "gas"),
  lithiumOre: resource("Lithium Ore", "t", 23, "raw", "ore"),
  goldOre: resource("Gold Ore", "t", 24, "raw", "secure"),
  silverOre: resource("Silver Ore", "t", 17, "raw", "secure"),
  sulfur: resource("Sulfur", "t", 13, "raw", "hazardous"),
  rareEarth: resource("Rare Earth Concentrate", "t", 25, "raw", "secure"),
  biomass: resource("Biomass", "t", 7, "raw", "general"),
  sand: resource("Sand", "t", 6, "raw", "ore"),
  tungstenOre: resource("Tungsten Ore", "t", 25, "raw", "ore"),
  ice: resource("Ice", "t", 8, "raw", "cold"),
  ironIngot: resource("Iron Ingot", "t", 42, "refined", "general"),
  copperIngot: resource("Copper Ingot", "t", 46, "refined", "general"),
  aluminumIngot: resource("Aluminum Ingot", "t", 52, "refined", "general"),
  coke: resource("Coke", "t", 34, "refined", "general"),
  siliconWafer: resource("Silicon Wafer", "wafer", 72, "refined", "secure"),
  refinedFuel: resource("Refined Fuel", "bbl", 38, "refined", "liquid"),
  purifiedWater: resource("Purified Water", "kL", 20, "refined", "liquid"),
  quicklime: resource("Quicklime", "t", 20, "construction", "general"),
  titaniumIngot: resource("Titanium Ingot", "t", 78, "refined", "general"),
  enrichedUranium: resource("Enriched Uranium", "rod", 100, "refined", "radioactive"),
  methane: resource("Methane", "kNm³", 44, "refined", "gas"),
  lithiumCarbonate: resource("Lithium Carbonate", "t", 84, "refined", "hazardous"),
  goldBar: resource("Gold Bar", "kg", 96, "refined", "secure"),
  silverBar: resource("Silver Bar", "kg", 68, "refined", "secure"),
  sulfuricAcid: resource("Sulfuric Acid", "kL", 62, "refined", "hazardous"),
  neodymium: resource("Neodymium", "kg", 88, "refined", "secure"),
  bioFuel: resource("Biofuel", "bbl", 36, "refined", "liquid"),
  glass: resource("Glass", "t", 85, "refined", "general"),
  hydrogen: resource("Hydrogen", "kNm³", 58, "refined", "gas"),
  tungstenCarbide: resource("Tungsten Carbide", "t", 98, "refined", "general"),
  steelPlate: resource("Steel Plate", "t", 75, "refined", "general"),
  copperWire: resource("Copper Wire", "t", 115, "refined", "general"),
  steelBeam: resource("Steel Beam", "t", 110, "component", "general"),
  plasticSheet: resource("Plastic Sheet", "t", 92, "component", "general"),
  basicCircuit: resource("Basic Circuit", "board", 140, "component", "secure"),
  concrete: resource("Concrete", "t", 30, "construction", "general"),
  titaniumPipe: resource("Titanium Pipe", "t", 160, "component", "general"),
  reinforcedGlass: resource("Reinforced Glass", "t", 170, "component", "general"),
  rubber: resource("Rubber", "t", 88, "component", "general"),
  fasteners: resource("Fasteners", "crate", 78, "component", "general"),
  electricMotor: resource("Electric Motor", "unit", 180, "component", "general"),
  hydraulicPump: resource("Hydraulic Pump", "unit", 210, "component", "general"),
  batteryCell: resource("Battery Cell", "module", 190, "component", "hazardous"),
  fiberglass: resource("Fiberglass", "t", 120, "component", "general"),
  coolantContainer: resource("Coolant Container", "unit", 125, "component", "hazardous"),
  solarCell: resource("Solar Cell", "panel", 220, "component", "secure"),
  gearbox: resource("Gearbox", "unit", 175, "component", "general"),
  insulatedCable: resource("Insulated Cable", "coil", 145, "component", "general"),
  combustionEngine: resource("Combustion Engine", "unit", 240, "component", "general"),
  fuelCell: resource("Fuel Cell", "stack", 250, "component", "hazardous"),
  microprocessor: resource("Microprocessor", "chip", 420, "advanced", "secure"),
  advancedAlloyPlate: resource("Advanced Alloy Plate", "t", 380, "advanced", "general"),
  highCapacityBatteryPack: resource("High-Capacity Battery Pack", "pack", 520, "advanced", "hazardous"),
  optoelectronicCable: resource("Optoelectronic Cable", "coil", 460, "advanced", "secure"),
  servoMechanism: resource("Servo Mechanism", "unit", 410, "advanced", "general"),
  controlModule: resource("Control Module", "module", 560, "advanced", "secure"),
  industrialRobotArm: resource("Industrial Robot Arm", "unit", 750, "advanced", "general"),
  pressureVessel: resource("Pressure Vessel", "unit", 680, "advanced", "hazardous"),
  pcb: resource("Printed Circuit Board", "board", 360, "advanced", "secure"),
  syntheticFiber: resource("Synthetic Fiber", "t", 340, "advanced", "general"),
  pneumaticValve: resource("Pneumatic Valve", "unit", 330, "advanced", "general"),
  sensorArray: resource("Sensor Array", "array", 620, "advanced", "secure"),
  superconductorAssembly: resource("Superconductor Assembly", "assembly", 980, "advanced", "secure"),
  fuelInjector: resource("Fuel Injector", "unit", 390, "advanced", "general"),
  radiatorPanel: resource("Radiator Panel", "panel", 430, "advanced", "general"),
  transformer: resource("Transformer", "unit", 470, "advanced", "general"),
  reinforcedChassis: resource("Reinforced Chassis", "frame", 690, "advanced", "general"),
  heatShieldTile: resource("Heat Shield Tile", "tile", 840, "advanced", "hazardous"),
  nuclearFuelRod: resource("Nuclear Fuel Rod", "rod", 1500, "advanced", "radioactive"),
  powerInverter: resource("Power Inverter", "unit", 540, "advanced", "general"),
  quantumProcessor: resource("Quantum Processor", "chip", 4200, "hightech", "secure"),
  compositeArmorPlate: resource("Composite Armor Plate", "plate", 3100, "hightech", "general"),
  fusionCoreMatrix: resource("Fusion Core Matrix", "matrix", 9800, "hightech", "hazardous"),
  rocketThruster: resource("Rocket Thruster", "unit", 6200, "hightech", "general"),
  satelliteBus: resource("Satellite Bus", "unit", 4800, "hightech", "secure"),
  lifeSupportAssembly: resource("Life Support Assembly", "assembly", 5300, "hightech", "cryogenic"),
  avionicsSuite: resource("Avionics Suite", "suite", 5700, "hightech", "secure"),
  orbitalHullSegment: resource("Orbital Hull Segment", "segment", 6100, "hightech", "general"),
  ionEngine: resource("Ion Engine", "unit", 7600, "hightech", "general"),
  electronics: resource("Electronics", "t", 240, "refined", "secure"),
  cryogenicTank: resource("Cryogenic Tank", "tank", 2900, "hightech", "cryogenic"),
  photovoltaicArray: resource("Photovoltaic Array", "array", 4400, "hightech", "general"),
  navigationModule: resource("Navigation Module", "module", 3600, "hightech", "secure"),
  reinforcedContainer: resource("Reinforced Container", "container", 2600, "hightech", "secure"),
  plasmaConduit: resource("Plasma Conduit", "conduit", 5000, "hightech", "hazardous"),
  electromagneticRail: resource("Electromagnetic Rail", "rail", 6800, "hightech", "general"),
  payloadBay: resource("Payload Bay", "bay", 3400, "hightech", "general"),
  telemetryArray: resource("Telemetry Array", "array", 3900, "hightech", "secure"),
  phone: resource("Phone", "unit", 420, "consumer", "secure"),
};

const createCentralInventory = (): GameState["warehouses"]["central"]["inventory"] => {
  const inventory = Object.fromEntries(
    (Object.keys(RESOURCE_DEFINITIONS) as ResourceId[]).map((resourceId) => [resourceId, { amount: 0, reserved: 0 }]),
  ) as GameState["warehouses"]["central"]["inventory"];

  const startingAmounts: Partial<Record<ResourceId, number>> = {
    power: 0,
    coal: 2000,
    ironOre: 80,
    ironIngot: 0,
    steelPlate: 100,
    quicklime: 40,
    water: 100,
    concrete: 100,
    copperOre: 0,
    copperWire: 0,
    silica: 0,
    glass: 0,
    electronics: 0,
    phone: 0,
  };

  for (const [resourceId, amount] of Object.entries(startingAmounts)) {
    inventory[resourceId as ResourceId].amount = amount ?? 0;
  }

  return inventory;
};

const FACILITIES = [
  fac("warehouse", "Warehouse", {}, {}, 0, 1_200, { concrete: 15 }, [], true, 1, 0, 1),
  fac("coalGenerator", "Coal Generator", { coal: 2 }, { power: 5 }, 0, 650, { steelPlate: 5 }, [], true, 3, 1, 1),
  fac("ironOreMine", "Iron Ore Mine", {}, { ironOre: 1.5 }, 1, 900, { concrete: 10 }, [], true, 2, 2, 1),
  fac("coalExcavator", "Coal Excavator", {}, { coal: 1.25 }, 1, 900, { concrete: 10 }, [], true, 2, 2, 1),
  fac("blastFurnace", "Blast Furnace", { ironOre: 1, coal: 1 }, { ironIngot: 1 }, 2, 1_500, { steelPlate: 8 }, req(2, "ironOreMine", "coalExcavator"), false, 5, 5, 2),
  fac("rollingMill", "Rolling Mill", { ironIngot: 1, coal: 0.5 }, { steelPlate: 1 }, 2, 2_200, { concrete: 15 }, req(2, "blastFurnace"), false, 6, 4, 3),
  fac("concreteBatchPlant", "Concrete Batch Plant", { quicklime: 1, water: 2 }, { concrete: 1 }, 1, 1_200, { steelPlate: 5 }, [], true, 3, 2, 1),
  fac("waterPump", "Water Pump", {}, { water: 4 }, 1, 850, { concrete: 8 }, [], true, 2, 2, 1),
  fac("quicklimeHarvester", "Quicklime Harvester", { water: 1 }, { quicklime: 1 }, 1, 1_100, { concrete: 10, steelPlate: 3 }, [], true, 2, 2, 1),
  fac("workerHousing", "Worker Housing", {}, {}, 1, 1_000, { concrete: 12, steelPlate: 4 }, [], true, 2, 0, 1),
  fac("solarPanels", "Solar Panels", {}, { power: 6 }, 0, 1_800, { steelPlate: 6, concrete: 8 }, [], true, 0, 0, 1),
  fac("windTurbines", "Wind Turbines", {}, { power: 4 }, 0, 2_400, { steelPlate: 10, concrete: 12 }, req(2, "rollingMill"), false, 0, 0, 2),
  fac("copperMine", "Copper Mine", {}, { copperOre: 1.2 }, 1, 1_050, { concrete: 12 }, [], true, 2, 2, 1),
  fac("wireMill", "Wire Mill", { copperOre: 1 }, { copperWire: 1 }, 2, 1_700, { steelPlate: 8, concrete: 10 }, req(2, "copperMine"), false, 5, 3, 2),
  fac("silicaQuarry", "Silica Quarry", {}, { silica: 1.5 }, 1, 950, { concrete: 10 }, [], true, 2, 2, 1),
  fac("glassworks", "Glassworks", { silica: 1, water: 1 }, { glass: 1 }, 2, 1_900, { steelPlate: 8, concrete: 12 }, req(2, "silicaQuarry"), false, 5, 3, 2),
  fac("electronicsAssembler", "Electronics Assembler", { copperWire: 1, glass: 0.5, steelPlate: 0.25 }, { electronics: 1 }, 3, 2_800, { steelPlate: 12, concrete: 15 }, req(2, "wireMill", "glassworks"), false, 8, 5, 4),
  fac("phoneFactory", "Phone Factory", { electronics: 1, steelPlate: 0.5 }, { phone: 1 }, 4, 4_500, { concrete: 18, steelPlate: 12 }, req(2, "electronicsAssembler"), false, 10, 6, 5),
  fac("bauxiteMine", "Bauxite Mine", {}, { bauxite: 1.3 }, 1, 1_050, { concrete: 12 }, [], true, 2, 2, 1),
  fac("oilRig", "Oil Rig", {}, { crudeOil: 1.1 }, 2, 1_650, { steelPlate: 8, concrete: 10 }, [], true, 3, 3, 1),
  fac("limestoneQuarry", "Limestone Quarry", {}, { limestone: 1.4 }, 1, 1_000, { concrete: 10 }, [], true, 2, 2, 1),
  fac("titaniumMine", "Titanium Mine", {}, { titaniumOre: 1 }, 2, 1_450, { steelPlate: 8, concrete: 12 }, [], true, 3, 3, 1),
  fac("uraniumMine", "Uranium Mine", {}, { uraniumOre: 0.7 }, 2, 1_950, { steelPlate: 10, concrete: 12 }, [], true, 4, 3, 1),
  fac("gasExtractionPlant", "Gas Extraction Plant", {}, { naturalGas: 1.2 }, 2, 1_500, { steelPlate: 8, concrete: 10 }, [], true, 3, 3, 1),
  fac("lithiumWell", "Lithium Well", {}, { lithiumOre: 0.8 }, 2, 1_500, { concrete: 12, steelPlate: 6 }, [], true, 3, 3, 1),
  fac("goldMine", "Gold Mine", {}, { goldOre: 0.7 }, 2, 1_700, { concrete: 10, steelPlate: 8 }, [], true, 4, 3, 1),
  fac("silverMine", "Silver Mine", {}, { silverOre: 0.9 }, 2, 1_550, { concrete: 10, steelPlate: 7 }, [], true, 3, 3, 1),
  fac("sulfurExtractor", "Sulfur Extractor", {}, { sulfur: 1.1 }, 1, 1_200, { concrete: 10 }, [], true, 2, 2, 1),
  fac("rareEarthMine", "Rare Earth Mine", {}, { rareEarth: 0.8 }, 2, 1_850, { steelPlate: 8, concrete: 12 }, [], true, 4, 3, 1),
  fac("biomassHarvester", "Biomass Harvester", {}, { biomass: 1.4 }, 1, 950, { concrete: 8, steelPlate: 4 }, [], true, 2, 2, 1),
  fac("sandDredge", "Sand Dredge", {}, { sand: 1.5 }, 1, 1_050, { concrete: 8, steelPlate: 5 }, [], true, 2, 2, 1),
  fac("glacierIceMine", "Glacier Ice Mine", {}, { ice: 1.2 }, 2, 1_650, { concrete: 10, steelPlate: 7 }, [], true, 3, 3, 1),
  fac("tungstenMine", "Tungsten Mine", {}, { tungstenOre: 0.75 }, 2, 1_900, { concrete: 12, steelPlate: 9 }, [], true, 4, 3, 1),
  fac("copperFoundry", "Copper Foundry", { copperOre: 1 }, { copperIngot: 0.9 }, 3, 1_800, { steelPlate: 8, concrete: 10 }, req(2, "copperMine"), false, 5, 4, 2),
  fac("aluminumSmelter", "Aluminum Smelter", { bauxite: 1 }, { aluminumIngot: 0.85 }, 3, 1_950, { steelPlate: 8, concrete: 10 }, req(2, "bauxiteMine"), false, 5, 4, 2),
  fac("cokeOven", "Coke Oven", { coal: 1 }, { coke: 0.85 }, 2, 1_650, { steelPlate: 7, concrete: 8 }, req(2, "coalExcavator"), false, 4, 3, 2),
  fac("quartzPurifier", "Quartz Purifier", { silica: 1, water: 0.25 }, { siliconWafer: 0.8 }, 3, 2_100, { steelPlate: 8, concrete: 10 }, req(2, "silicaQuarry"), false, 5, 4, 2),
  fac("oilRefinery", "Oil Refinery", { crudeOil: 1 }, { refinedFuel: 0.8 }, 4, 2_400, { steelPlate: 10, concrete: 12 }, req(2, "oilRig"), false, 6, 4, 2),
  fac("waterPurificationPlant", "Water Purification Plant", { water: 1 }, { purifiedWater: 0.9 }, 2, 1_600, { steelPlate: 6, concrete: 10 }, req(2, "waterPump"), false, 4, 3, 2),
  fac("limeKiln", "Lime Kiln", { limestone: 1 }, { quicklime: 0.85 }, 2, 1_700, { steelPlate: 7, concrete: 10 }, req(2, "limestoneQuarry"), false, 4, 3, 2),
  fac("titaniumSmelter", "Titanium Smelter", { titaniumOre: 1 }, { titaniumIngot: 0.8 }, 4, 2_550, { steelPlate: 10, concrete: 12 }, req(2, "titaniumMine"), false, 6, 4, 2),
  fac("centrifuge", "Centrifuge", { uraniumOre: 0.5 }, { enrichedUranium: 0.35 }, 4, 2_900, { steelPlate: 12, concrete: 12 }, req(2, "uraniumMine"), false, 7, 4, 2),
  fac("gasCracker", "Gas Cracker", { naturalGas: 1 }, { methane: 0.8, hydrogen: 0.35 }, 3, 2_350, { steelPlate: 10, concrete: 10 }, req(2, "gasExtractionPlant"), false, 5, 4, 2),
  fac("lithiumProcessor", "Lithium Processor", { lithiumOre: 1, water: 0.3 }, { lithiumCarbonate: 0.7 }, 3, 2_450, { steelPlate: 9, concrete: 11 }, req(2, "lithiumWell"), false, 5, 4, 2),
  fac("preciousMetalRefinery", "Precious Metal Refinery", { goldOre: 0.6, silverOre: 0.6 }, { goldBar: 0.3, silverBar: 0.3 }, 3, 2_700, { steelPlate: 10, concrete: 12 }, req(2, "goldMine", "silverMine"), false, 6, 4, 2),
  fac("acidPlant", "Acid Plant", { sulfur: 0.8, water: 0.6 }, { sulfuricAcid: 0.8 }, 3, 2_250, { steelPlate: 9, concrete: 10 }, req(2, "sulfurExtractor"), false, 5, 4, 2),
  fac("rareEarthSeparator", "Rare Earth Separator", { rareEarth: 0.8 }, { neodymium: 0.5 }, 4, 2_800, { steelPlate: 10, concrete: 12 }, req(2, "rareEarthMine"), false, 6, 4, 2),
  fac("biofuelPlant", "Biofuel Plant", { biomass: 1, water: 0.5 }, { bioFuel: 0.8 }, 3, 2_000, { steelPlate: 8, concrete: 10 }, req(2, "biomassHarvester"), false, 4, 3, 2),
  fac("glassPanePlant", "Glass Pane Plant", { sand: 1, purifiedWater: 0.25 }, { glass: 0.9 }, 3, 2_100, { steelPlate: 8, concrete: 10 }, req(2, "sandDredge", "waterPurificationPlant"), false, 5, 4, 2),
  fac("tungstenProcessor", "Tungsten Processor", { tungstenOre: 0.7, coke: 0.3 }, { tungstenCarbide: 0.5 }, 4, 2_950, { steelPlate: 12, concrete: 12 }, req(2, "tungstenMine", "cokeOven"), false, 7, 4, 2),
  fac("steelBeamMill", "Steel Beam Mill", { steelPlate: 1 }, { steelBeam: 0.7 }, 3, 2_400, { steelPlate: 8, concrete: 10 }, req(2, "rollingMill"), false, 5, 4, 3),
  fac("polymerPlant", "Polymer Plant", { refinedFuel: 0.8 }, { plasticSheet: 0.6, syntheticFiber: 0.2 }, 4, 2_900, { steelPlate: 10, concrete: 12 }, req(2, "oilRefinery"), false, 6, 4, 3),
  fac("circuitShop", "Circuit Shop", { copperWire: 0.8, siliconWafer: 0.6 }, { basicCircuit: 0.45 }, 4, 3_100, { steelPlate: 10, concrete: 12 }, req(2, "wireMill", "quartzPurifier"), false, 7, 5, 3),
  fac("pipeMill", "Pipe Mill", { titaniumIngot: 0.8 }, { titaniumPipe: 0.6 }, 4, 3_100, { steelPlate: 10, concrete: 12 }, req(2, "titaniumSmelter"), false, 6, 4, 3),
  fac("rubberVulcanizer", "Rubber Vulcanizer", { bioFuel: 0.5, sulfur: 0.3 }, { rubber: 0.5 }, 3, 2_700, { steelPlate: 8, concrete: 10 }, req(2, "biofuelPlant", "sulfurExtractor"), false, 5, 4, 3),
  fac("hardwarePress", "Hardware Press", { steelPlate: 0.7 }, { fasteners: 0.8 }, 3, 2_450, { steelPlate: 8, concrete: 10 }, req(2, "rollingMill"), false, 5, 4, 3),
  fac("motorFactory", "Motor Factory", { copperWire: 0.5, steelBeam: 0.4, fasteners: 0.3 }, { electricMotor: 0.35 }, 5, 3_500, { steelPlate: 12, concrete: 14 }, req(2, "steelBeamMill", "hardwarePress", "wireMill"), false, 8, 5, 3),
  fac("pumpAssembler", "Pump Assembler", { steelPlate: 0.4, titaniumPipe: 0.5, electricMotor: 0.2 }, { hydraulicPump: 0.3 }, 5, 3_700, { steelPlate: 12, concrete: 14 }, req(2, "pipeMill", "motorFactory"), false, 8, 5, 3),
  fac("batteryFactory", "Battery Factory", { lithiumCarbonate: 0.6, copperWire: 0.3 }, { batteryCell: 0.45 }, 5, 3_900, { steelPlate: 12, concrete: 14 }, req(2, "lithiumProcessor", "wireMill"), false, 8, 5, 3),
  fac("fiberglassMill", "Fiberglass Mill", { glass: 0.7, plasticSheet: 0.3 }, { fiberglass: 0.35, reinforcedGlass: 0.25 }, 4, 3_250, { steelPlate: 10, concrete: 12 }, req(2, "glassPanePlant", "polymerPlant"), false, 7, 4, 3),
  fac("coolantFactory", "Coolant Factory", { purifiedWater: 0.8, hydrogen: 0.2 }, { coolantContainer: 0.4 }, 4, 2_950, { steelPlate: 10, concrete: 12 }, req(2, "waterPurificationPlant", "gasCracker"), false, 6, 4, 3),
  fac("solarCellPlant", "Solar Cell Plant", { siliconWafer: 0.7, copperWire: 0.3 }, { solarCell: 0.4 }, 4, 3_400, { steelPlate: 10, concrete: 12 }, req(2, "quartzPurifier", "wireMill"), false, 7, 4, 3),
  fac("machiningShop", "Machining Shop", { steelBeam: 0.5, fasteners: 0.5 }, { gearbox: 0.35 }, 4, 3_200, { steelPlate: 10, concrete: 12 }, req(2, "steelBeamMill", "hardwarePress"), false, 7, 4, 3),
  fac("cableInsulationPlant", "Cable Insulation Plant", { copperWire: 0.7, rubber: 0.3 }, { insulatedCable: 0.5 }, 4, 3_100, { steelPlate: 10, concrete: 12 }, req(2, "wireMill", "rubberVulcanizer"), false, 7, 4, 3),
  fac("engineWorks", "Engine Works", { electricMotor: 0.3, gearbox: 0.3, refinedFuel: 0.4 }, { combustionEngine: 0.25 }, 5, 4_100, { steelPlate: 12, concrete: 14 }, req(2, "motorFactory", "machiningShop", "oilRefinery"), false, 9, 5, 3),
  fac("fuelCellPlant", "Fuel Cell Plant", { hydrogen: 0.5, copperWire: 0.25, refinedFuel: 0.2 }, { fuelCell: 0.3, power: 1.5 }, 4, 4_250, { steelPlate: 12, concrete: 14 }, req(2, "gasCracker", "wireMill", "oilRefinery"), false, 8, 5, 3),
  fac("alloyFoundry", "Alloy Foundry", { titaniumIngot: 0.5, tungstenCarbide: 0.3, aluminumIngot: 0.4 }, { advancedAlloyPlate: 0.35 }, 6, 4_600, { steelPlate: 14, concrete: 16 }, req(2, "titaniumSmelter", "tungstenProcessor", "aluminumSmelter"), false, 10, 6, 3),
  fac("valveWorkshop", "Valve Workshop", { steelPlate: 0.4, rubber: 0.2, titaniumPipe: 0.2 }, { pneumaticValve: 0.3 }, 4, 3_350, { steelPlate: 10, concrete: 12 }, req(2, "rollingMill", "rubberVulcanizer", "pipeMill"), false, 7, 4, 3),
  fac("transformerPlant", "Transformer Plant", { copperWire: 0.6, steelPlate: 0.3, insulatedCable: 0.3 }, { transformer: 0.3 }, 5, 3_800, { steelPlate: 12, concrete: 14 }, req(2, "wireMill", "cableInsulationPlant"), false, 8, 5, 3),
  fac("chassisAssembly", "Chassis Assembly", { steelBeam: 0.6, advancedAlloyPlate: 0.2, fasteners: 0.4 }, { reinforcedChassis: 0.25 }, 5, 4_400, { steelPlate: 14, concrete: 16 }, req(2, "steelBeamMill", "alloyFoundry", "hardwarePress"), false, 9, 5, 3),
  fac("semiconductorCleanroom", "Semiconductor Cleanroom", { siliconWafer: 0.6, goldBar: 0.15, purifiedWater: 0.4 }, { microprocessor: 0.25 }, 7, 5_500, { electronics: 3, steelPlate: 12, concrete: 16 }, req(2, "quartzPurifier", "preciousMetalRefinery", "waterPurificationPlant"), false, 12, 7, 4),
  fac("batteryPackPlant", "Battery Pack Plant", { batteryCell: 0.8, fiberglass: 0.2 }, { highCapacityBatteryPack: 0.3 }, 6, 5_200, { electronics: 2, steelPlate: 12, concrete: 16 }, req(2, "batteryFactory", "fiberglassMill"), false, 11, 6, 4),
  fac("fiberOpticsWorks", "Fiber Optics Works", { glass: 0.5, insulatedCable: 0.4, syntheticFiber: 0.2 }, { optoelectronicCable: 0.3 }, 6, 5_100, { electronics: 2, steelPlate: 12, concrete: 16 }, req(2, "glassPanePlant", "cableInsulationPlant", "polymerPlant"), false, 11, 6, 4),
  fac("roboticsFactory", "Robotics Factory", { electricMotor: 0.4, hydraulicPump: 0.2, reinforcedChassis: 0.2 }, { industrialRobotArm: 0.12, servoMechanism: 0.18 }, 8, 6_800, { electronics: 3, steelPlate: 14, concrete: 18 }, req(2, "motorFactory", "pumpAssembler", "chassisAssembly"), false, 14, 8, 4),
  fac("controlSystemFacility", "Control System Facility", { basicCircuit: 0.6, microprocessor: 0.2, insulatedCable: 0.3 }, { controlModule: 0.25 }, 7, 6_100, { electronics: 3, steelPlate: 12, concrete: 16 }, req(2, "circuitShop", "semiconductorCleanroom", "cableInsulationPlant"), false, 12, 7, 4),
  fac("vesselFabricationYard", "Vessel Fabrication Yard", { titaniumPipe: 0.5, advancedAlloyPlate: 0.3, reinforcedGlass: 0.2 }, { pressureVessel: 0.22 }, 8, 6_500, { electronics: 2, steelPlate: 14, concrete: 18 }, req(2, "pipeMill", "alloyFoundry", "fiberglassMill"), false, 13, 8, 4),
  fac("pcbAssemblyLine", "PCB Assembly Line", { basicCircuit: 0.6, copperWire: 0.3, glass: 0.2 }, { pcb: 0.35 }, 6, 5_400, { electronics: 2, steelPlate: 12, concrete: 16 }, req(2, "circuitShop", "wireMill", "glassworks"), false, 11, 6, 4),
  fac("superconductorLab", "Superconductor Lab", { neodymium: 0.2, goldBar: 0.2, hydrogen: 0.2 }, { superconductorAssembly: 0.15 }, 9, 7_800, { electronics: 4, steelPlate: 15, concrete: 20 }, req(2, "rareEarthSeparator", "preciousMetalRefinery", "gasCracker"), false, 16, 8, 4),
  fac("sensorCleanroom", "Sensor Cleanroom", { siliconWafer: 0.4, glass: 0.2, goldBar: 0.1 }, { sensorArray: 0.25 }, 7, 6_300, { electronics: 3, steelPlate: 12, concrete: 16 }, req(2, "quartzPurifier", "glassPanePlant", "preciousMetalRefinery"), false, 12, 7, 4),
  fac("fuelInjectorLine", "Fuel Injector Line", { combustionEngine: 0.2, pneumaticValve: 0.25, fasteners: 0.2 }, { fuelInjector: 0.2 }, 6, 5_700, { electronics: 2, steelPlate: 12, concrete: 16 }, req(2, "engineWorks", "valveWorkshop", "hardwarePress"), false, 11, 6, 4),
  fac("radiatorWorks", "Radiator Works", { aluminumIngot: 0.4, copperWire: 0.3, purifiedWater: 0.2 }, { radiatorPanel: 0.25 }, 6, 5_600, { electronics: 2, steelPlate: 12, concrete: 16 }, req(2, "aluminumSmelter", "wireMill", "waterPurificationPlant"), false, 11, 6, 4),
  fac("powerElectronicsPlant", "Power Electronics Plant", { pcb: 0.35, insulatedCable: 0.3, transformer: 0.2 }, { powerInverter: 0.2 }, 7, 6_200, { electronics: 3, steelPlate: 13, concrete: 16 }, req(2, "pcbAssemblyLine", "cableInsulationPlant", "transformerPlant"), false, 12, 7, 4),
  fac("quantumComputerLab", "Quantum Computer Lab", { microprocessor: 0.3, superconductorAssembly: 0.15, controlModule: 0.2 }, { quantumProcessor: 0.12 }, 10, 8_800, { electronics: 5, steelPlate: 16, concrete: 20 }, req(2, "semiconductorCleanroom", "superconductorLab", "controlSystemFacility"), false, 18, 9, 4),
  fac("compositeFoundry", "Composite Foundry", { advancedAlloyPlate: 0.3, fiberglass: 0.2, plasticSheet: 0.2 }, { compositeArmorPlate: 0.14, heatShieldTile: 0.12 }, 8, 7_100, { electronics: 4, steelPlate: 14, concrete: 18 }, req(2, "alloyFoundry", "fiberglassMill", "polymerPlant"), false, 14, 8, 4),
  fac("matrixIntegrationPlant", "Matrix Integration Plant", { highCapacityBatteryPack: 0.2, powerInverter: 0.15, superconductorAssembly: 0.1 }, { fusionCoreMatrix: 0.1 }, 10, 9_500, { electronics: 5, steelPlate: 16, concrete: 20 }, req(2, "batteryPackPlant", "powerElectronicsPlant", "superconductorLab"), false, 19, 9, 4),
  fac("rocketEngineFacility", "Rocket Engine Facility", { advancedAlloyPlate: 0.25, combustionEngine: 0.2, fuelInjector: 0.1 }, { rocketThruster: 0.12 }, 9, 8_300, { electronics: 4, steelPlate: 15, concrete: 20 }, req(2, "alloyFoundry", "engineWorks", "fuelInjectorLine"), false, 17, 8, 4),
  fac("satelliteHangar", "Satellite Hangar", { controlModule: 0.2, compositeArmorPlate: 0.15, sensorArray: 0.15 }, { satelliteBus: 0.1, telemetryArray: 0.08, photovoltaicArray: 0.06 }, 11, 10_200, { electronics: 6, steelPlate: 18, concrete: 22 }, req(2, "controlSystemFacility", "compositeFoundry", "sensorCleanroom"), false, 21, 10, 5),
  fac("nuclearFuelFabricator", "Nuclear Fuel Fabricator", { enrichedUranium: 0.25, advancedAlloyPlate: 0.12, pressureVessel: 0.05 }, { nuclearFuelRod: 0.12, power: 4 }, 8, 10_800, { electronics: 6, steelPlate: 18, concrete: 22 }, req(2, "centrifuge", "alloyFoundry", "vesselFabricationYard"), false, 22, 9, 5),
  fac("orbitalHullFabricator", "Orbital Hull Fabricator", { compositeArmorPlate: 0.2, reinforcedChassis: 0.15, advancedAlloyPlate: 0.15 }, { orbitalHullSegment: 0.08, reinforcedContainer: 0.08, payloadBay: 0.06 }, 11, 10_500, { electronics: 6, steelPlate: 18, concrete: 22 }, req(2, "compositeFoundry", "chassisAssembly", "alloyFoundry"), false, 21, 10, 5),
  fac("ionPropulsionLab", "Ion Propulsion Lab", { quantumProcessor: 0.06, powerInverter: 0.1, superconductorAssembly: 0.05 }, { ionEngine: 0.07, plasmaConduit: 0.08, electromagneticRail: 0.05 }, 12, 11_400, { electronics: 7, steelPlate: 20, concrete: 24 }, req(2, "quantumComputerLab", "powerElectronicsPlant", "superconductorLab"), false, 23, 10, 5),
  fac("avionicsWorkshop", "Avionics Workshop", { electronics: 0.25, controlModule: 0.15, sensorArray: 0.1 }, { avionicsSuite: 0.09, navigationModule: 0.08 }, 10, 9_900, { electronics: 5, steelPlate: 17, concrete: 21 }, req(2, "electronicsAssembler", "controlSystemFacility", "sensorCleanroom"), false, 20, 9, 5),
  fac("lifeSupportWorks", "Life Support Works", { pressureVessel: 0.12, syntheticFiber: 0.12, fuelCell: 0.1 }, { lifeSupportAssembly: 0.08, cryogenicTank: 0.07 }, 10, 10_000, { electronics: 5, steelPlate: 17, concrete: 21 }, req(2, "vesselFabricationYard", "polymerPlant", "fuelCellPlant"), false, 20, 9, 5),
  fac("oreSilo", "Ore Silo", {}, {}, 0, 1_400, { concrete: 10, steelPlate: 4 }, [], true, 1, 0, 1),
  fac("liquidStorageTank", "Liquid Storage Tank", {}, {}, 0, 1_600, { concrete: 12, steelPlate: 5 }, [], true, 1, 0, 1),
  fac("gasGasholder", "Gas Gasholder", {}, {}, 0, 1_800, { concrete: 12, steelPlate: 6 }, req(2, "gasExtractionPlant"), false, 1, 0, 1),
  fac("hazardousVault", "Hazardous Vault", {}, {}, 1, 2_200, { concrete: 14, steelPlate: 8 }, req(2, "acidPlant"), false, 2, 1, 3),
  fac("highSecurityVault", "High-Security Vault", {}, {}, 1, 2_600, { concrete: 14, steelPlate: 10 }, req(2, "electronicsAssembler"), false, 2, 1, 3),
  fac("radioactiveVault", "Radioactive Vault", {}, {}, 1, 3_200, { concrete: 16, steelPlate: 12 }, req(2, "uraniumMine"), false, 3, 1, 4),
  fac("cryogenicStorageTank", "Cryogenic Storage Tank", {}, {}, 1, 3_600, { concrete: 16, steelPlate: 12 }, req(2, "fuelCellPlant"), false, 3, 1, 4),
  fac("megaWarehouseArray", "Mega Warehouse Array", {}, {}, 2, 8_500, { concrete: 24, steelPlate: 18, electronics: 4 }, req(2, "chassisAssembly"), false, 4, 1, 5),
] as const;
=======
const inventoryEntry = (amount: number) => ({
  amount,
  reserved: 0,
  autoSell: {
    enabled: false,
    amount: 0,
  },
});
>>>>>>> origin/master

export const INITIAL_GAME_STATE: GameState = {
  schemaVersion: 1,
  cash: 25_000,
  power: { available: 0, productionPerSecond: 0, consumptionPerSecond: 0 },
  workforce: { capacity: 20, activeDemand: 0 },
  cashFlow: { upkeep: 0, wages: 0, net: 0 },
  warehouses: {
<<<<<<< HEAD
    central: { capacity: 20000, inventory: createCentralInventory() },
    energy: { capacity: 250, inventory: { power: { amount: 50, reserved: 0 } } },
=======
    central: {
      capacity: 20000,
      inventory: {
        power: inventoryEntry(0),
        coal: inventoryEntry(2000),
        ironOre: inventoryEntry(80),
        ironIngot: inventoryEntry(0),
        steelPlate: inventoryEntry(100),
        quicklime: inventoryEntry(40),
        water: inventoryEntry(100),
        concrete: inventoryEntry(100),
        copperOre: inventoryEntry(0),
        copperWire: inventoryEntry(0),
        silica: inventoryEntry(0),
        glass: inventoryEntry(0),
        electronics: inventoryEntry(0),
        phone: inventoryEntry(0),
      },
    },
    energy: {
      capacity: 250,
      inventory: {
        power: inventoryEntry(50),
      },
    },
  },
  facilities: {
    // [] means "available from the start"; the two-level rules below form the
    // production-chain progression for advanced facilities.
    warehouse: facility("warehouse", "Warehouse", {}, {}, 0, 1_200, { concrete: 15 }, [], true, 1, 0),
    coalGenerator: facility("coalGenerator", "Coal Generator", { coal: 2 }, { power: 5 }, 0, 650, { steelPlate: 5 }, [], true, 3, 1),
    ironOreMine: facility("ironOreMine", "Iron Ore Mine", {}, { ironOre: 1.5 }, 1, 900, { concrete: 10 }, [], true, 2, 2),
    coalExcavator: facility("coalExcavator", "Coal Excavator", {}, { coal: 1.25 }, 1, 900, { concrete: 10 }, [], true, 2, 2),
    blastFurnace: facility("blastFurnace", "Blast Furnace", { ironOre: 1, coal: 1 }, { ironIngot: 1 }, 2, 1_500, { steelPlate: 8 }, [{ facilityId: "ironOreMine", level: 2 }, { facilityId: "coalExcavator", level: 2 }], false, 5, 5),
    rollingMill: facility("rollingMill", "Rolling Mill", { ironIngot: 1, coal: 0.5 }, { steelPlate: 1 }, 2, 2_200, { concrete: 15 }, [{ facilityId: "blastFurnace", level: 2 }], false, 6, 4),
    concreteBatchPlant: facility("concreteBatchPlant", "Concrete Batch Plant", { quicklime: 1, water: 2 }, { concrete: 1 }, 1, 1_200, { steelPlate: 5 }, [], true, 3, 2),
    waterPump: facility("waterPump", "Water Pump", {}, { water: 4 }, 1, 850, { concrete: 8 }, [], true, 2, 2),
    quicklimeHarvester: facility("quicklimeHarvester", "Quicklime Harvester", { water: 1 }, { quicklime: 1 }, 1, 1_100, { concrete: 10, steelPlate: 3 }, [], true, 2, 2),
    solarPanels: facility("solarPanels", "Solar Panels", {}, { power: 6 }, 0, 1_800, { steelPlate: 6, concrete: 8 }, [], true, 0, 0),
    windTurbines: facility("windTurbines", "Wind Turbines", {}, { power: 4 }, 0, 2_400, { steelPlate: 10, concrete: 12 }, [{ facilityId: "rollingMill", level: 2 }], false, 0, 0),
    workerHousing: facility("workerHousing", "Worker Housing", {}, {}, 1, 1_000, { concrete: 12, steelPlate: 4 }, [], true, 2, 0),
    copperMine: facility("copperMine", "Copper Mine", {}, { copperOre: 1.2 }, 1, 1_050, { concrete: 12 }, [], true, 2, 2),
    wireMill: facility("wireMill", "Wire Mill", { copperOre: 1 }, { copperWire: 1 }, 2, 1_700, { steelPlate: 8, concrete: 10 }, [{ facilityId: "copperMine", level: 2 }], false, 5, 3),
    silicaQuarry: facility("silicaQuarry", "Silica Quarry", {}, { silica: 1.5 }, 1, 950, { concrete: 10 }, [], true, 2, 2),
    glassworks: facility("glassworks", "Glassworks", { silica: 1, water: 1 }, { glass: 1 }, 2, 1_900, { steelPlate: 8, concrete: 12 }, [{ facilityId: "silicaQuarry", level: 2 }], false, 5, 3),
    electronicsAssembler: facility("electronicsAssembler", "Electronics Assembler", { copperWire: 1, glass: 0.5, steelPlate: 0.25 }, { electronics: 1 }, 3, 2_800, { steelPlate: 12, concrete: 15 }, [{ facilityId: "wireMill", level: 2 }, { facilityId: "glassworks", level: 2 }], false, 8, 5),
    phoneFactory: facility("phoneFactory", "Phone Factory", { electronics: 1, steelPlate: 0.5 }, { phone: 1 }, 4, 4_500, { concrete: 18, steelPlate: 12 }, [{ facilityId: "electronicsAssembler", level: 2 }], false, 10, 6),
>>>>>>> origin/master
  },
  facilities: Object.fromEntries(FACILITIES.map((facility) => [facility.id, facility])) as GameState["facilities"],
  lastTickTimestamp: 0,
  lastSavedTimestamp: 0,
};

