/// <reference types="vite/client" />
// Pixel-art lookup. Sprites are generated by `node scripts/generate-pixel-art.mjs`
// (named "<shape>-<tint>.svg"). Every lookup falls back gracefully for unknown IDs.

const SPRITES = import.meta.glob("./*.svg", { eager: true, query: "?url", import: "default" }) as Record<string, string>;

const sprite = (name: string): string | undefined => SPRITES[`./${name}.svg`];

export const LOGO_ART = sprite("logo") ?? "";

export const FALLBACK_ART = sprite("crate-steel") ?? "";

const RESOURCE_SPRITES: Record<string, string> = {
  power: "bolt-amber", coal: "ore-coal", ironOre: "ore-iron", copperOre: "ore-copper", bauxite: "ore-bauxite",
  silica: "crystal-silica", crudeOil: "drop-oil", water: "drop-water", limestone: "ore-lime", titaniumOre: "ore-titanium",
  uraniumOre: "ore-uranium", naturalGas: "canister-gas", lithiumOre: "ore-lithium", goldOre: "ore-gold", silverOre: "ore-silver",
  sulfur: "pile-sulfur", rareEarth: "crystal-rare", biomass: "pile-bio", sand: "pile-sand", tungstenOre: "ore-tungsten",
  ice: "crystal-water",
  ironIngot: "ingot-steel", copperIngot: "ingot-copper", aluminumIngot: "ingot-alu", coke: "pile-coal", siliconWafer: "plate-silica",
  refinedFuel: "drop-fuel", purifiedWater: "drop-cyan", quicklime: "pile-lime", titaniumIngot: "ingot-titanium",
  enrichedUranium: "orb-uranium", methane: "canister-cyan", lithiumCarbonate: "pile-lithium", goldBar: "ingot-gold",
  silverBar: "ingot-silver", sulfuricAcid: "drop-sulfur", neodymium: "ingot-rare", bioFuel: "drop-bio", glass: "plate-silica",
  hydrogen: "canister-silver", tungstenCarbide: "ingot-tungsten", steelPlate: "plate-steel", copperWire: "coil-copper",
  electronics: "chip-copper",
  steelBeam: "beam-steel", plasticSheet: "plate-plastic", basicCircuit: "chip-circuit", concrete: "plate-concrete",
  titaniumPipe: "beam-titanium", reinforcedGlass: "plate-gas", rubber: "pile-rubber", fasteners: "crate-steel",
  electricMotor: "gear-copper", hydraulicPump: "gear-red", batteryCell: "battery-amber", fiberglass: "coil-silica",
  coolantContainer: "canister-water", solarCell: "plate-cyan", gearbox: "gear-steel", insulatedCable: "coil-rubber",
  combustionEngine: "gear-iron", fuelCell: "battery-cyan",
  microprocessor: "chip-cyan", advancedAlloyPlate: "plate-titanium", highCapacityBatteryPack: "battery-circuit",
  optoelectronicCable: "coil-cyan", servoMechanism: "gear-titanium", controlModule: "chip-amber",
  industrialRobotArm: "gear-amber", pressureVessel: "canister-steel", pcb: "chip-gold", syntheticFiber: "coil-plastic",
  pneumaticValve: "gear-cyan", sensorArray: "chip-red", superconductorAssembly: "orb-cyan", fuelInjector: "canister-fuel",
  radiatorPanel: "plate-red", transformer: "battery-copper", reinforcedChassis: "beam-tungsten", heatShieldTile: "plate-coal",
  nuclearFuelRod: "rods-uranium", powerInverter: "battery-steel",
  quantumProcessor: "chip-purple", compositeArmorPlate: "plate-tungsten", fusionCoreMatrix: "orb-purple",
  rocketThruster: "rocket-red", satelliteBus: "rocket-cyan", lifeSupportAssembly: "canister-bio", avionicsSuite: "chip-silver",
  orbitalHullSegment: "plate-silver", ionEngine: "rocket-purple", cryogenicTank: "canister-silica",
  photovoltaicArray: "plate-cyan", navigationModule: "orb-water", reinforcedContainer: "crate-tungsten",
  plasmaConduit: "beam-purple", electromagneticRail: "beam-cyan", payloadBay: "crate-silver", telemetryArray: "orb-circuit",
  phone: "phone-coal",
};

const CATEGORY_SPRITES: Record<string, string> = {
  energy: "bolt-amber", raw: "ore-steel", refined: "ingot-steel", component: "gear-steel", advanced: "chip-cyan",
  hightech: "orb-purple", construction: "plate-concrete", consumer: "phone-coal",
};

const FACILITY_SPRITES: Record<string, string> = {
  warehouse: "warehouse-steel", megaWarehouseArray: "warehouse-amber", workerHousing: "housing-brick",
  coalGenerator: "power-concrete", solarPanels: "solar-cyan", windTurbines: "wind-steel", oreSilo: "tank-concrete",
  liquidStorageTank: "tank-water", gasGasholder: "tank-gas", cryogenicStorageTank: "tank-silica",
  hazardousVault: "vault-amber", highSecurityVault: "vault-gold", radioactiveVault: "vault-uranium",
  oilRig: "rig-oil", waterPump: "rig-water", lithiumWell: "rig-lithium", gasExtractionPlant: "rig-gas",
};

// Keyword rules for facilities without an explicit entry (first match wins).
const FACILITY_RULES: Array<[RegExp, string]> = [
  [/Lab$|Cleanroom$/, "lab-cyan"],
  [/Mine$|Quarry$|Excavator$|Dredge$|Harvester$|Extractor$/, "mine-earth"],
  [/Furnace$|Smelter$|Foundry$|Oven$|Kiln$|Fabricator$/, "furnace-brick"],
  [/Refinery$|Cracker$|Purifier$|centrifuge|Separator$|Processor$|acidPlant|biofuelPlant|polymerPlant|coolantFactory|Purification/, "plant-steel"],
];

export const getResourceArt = (resourceId: string, category?: string): string =>
  sprite(RESOURCE_SPRITES[resourceId] ?? "") ?? sprite(CATEGORY_SPRITES[category ?? ""] ?? "") ?? FALLBACK_ART;

export const getFacilityArt = (facilityId: string): string => {
  const name = FACILITY_SPRITES[facilityId] ?? FACILITY_RULES.find(([pattern]) => pattern.test(facilityId))?.[1] ?? "factory-steel";
  return sprite(name) ?? sprite("factory-steel") ?? FALLBACK_ART;
};

const TAB_SPRITES: Record<string, string> = {
  dashboard: "tab-gauge", facilities: "factory-steel", warehouse: "crate-wood", market: "tab-chart", settings: "tab-save",
};

export const getTabArt = (tabId: string): string => sprite(TAB_SPRITES[tabId] ?? "") ?? FALLBACK_ART;
